### ISSUE TITLE
Using functorch and torchdim side by side

### ISSUE THREAD

**Issue by ThomasHeap** [facebookresearch/torchdim#8]
Is it possible to use torchdim and functorch at the same time? If I install functorch after installing torchdim and then run my code which imports vmap from functorch I get the attached core dump error.
[coredump.txt](https://github.com/facebookresearch/torchdim/files/9200625/coredump.txt)

I see this is probably related to the CppExtension being applied in setup.py.

Thank you

**Comment by zdevito** [comment]
If you have functorch installed already, you can build a version of torchdim that will work with it by setting `build_functorch=False` here:

https://github.com/facebookresearch/torchdim/blob/main/setup.py#L17

Our tentative plan is to merge this code into the functorch codebase so that they work together correctly by default.

**Comment by ThomasHeap** [comment]
Ah thank you!
